---

- name: Add nodesource apt_keys
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_major_version }}.x {{ ansible_distribution_release }} main"
    state: present


- name: Install node-red dependencies
  action: apt pkg={{ item }} state=latest update_cache=yes
  with_items:
   - nodejs
   - nginx
   - libavahi-compat-libdnssd-dev

- name: Create non-priviledged user to run node-red
  user: >
    name=node-red
    append=yes
    groups=users

- name: "Install Node-RED node.js package globally. Takes a few minutes."
  command: npm install -g --unsafe-perm node-red
  
# TODO: replace the above line, needs ansible 2.8
# - name: Install "node-red" node.js package. Takes a few minutes!
#   npm:
#     name: node-red
#     unsafe_perm: true
#     global: yes
#     state: latest

- name: "Install Node-RED packages (flows, nodes)"
  npm:
    name: "{{ item }}"
    state: latest
  #become: yes
  with_items: "{{ nodered_packages }}"

- name: Setup a systemd service for node-red
  template: >
    src=nodered.service.j2
    dest=/lib/systemd/system/node-red.service

- name: Enable and start the node-red systemd service
  service: >
    name=node-red
    enabled=yes
    state=started

- name: Create nginx proxy
  template:
    src: nodered-nginx.conf
    dest: /etc/nginx/sites-available/node-red

- name: Enable node-red nginx config
  file:
    src: /etc/nginx/sites-available/node-red
    dest: /etc/nginx/sites-enabled/node-red
    state: link

- name: Restart node-RED
  service: >
    name=node-red
    state=restarted

- name: Restart nginx
  service: >
    name=nginx
    enabled=yes
    state=restarted
