---

- name: Add nodesource apt_keys
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- apt_repository:
    repo: "deb https://deb.nodesource.com/node_8.x {{ ansible_distribution_release }} main"
    state: present


- name: Install node-red dependencies
  action: apt pkg={{ item }} state=latest update_cache=yes
  with_items:
   - nodejs
   - nginx
   - libavahi-compat-libdnssd-dev

- name: Create non-priviledged user to run node-red
  user: >
    name=node-red
    append=yes
    groups=users


- name: Install "Node-RED" node.js package globally.
  command: npm install -g --unsafe-perm node-red

- name: Install "node-red-node-email"
  command: npm install -g node-red-node-email

- name: Install "node-red-contrib-matrixbot"
  command: npm install -g node-red-contrib-matrixbot

- name: Install "node-red-node-ping"
  command: npm install -g node-red-node-ping
  
#  npm:
#    name: node-red
#    global: yes
#    state: latest

#- name: Clone node-red from github
#  git: repo=https://github.com/node-red/node-red.git dest=/opt/node-red version={{ nodered_version }}

#- name: Globally install grunt-cli
#  command: npm install -g grunt-cli
#  args:
#    chdir: /opt/node-red 

#- name: Call grunt-build
#  command: grunt build
#  args:
#    chdir: /opt/node-red 

#- name: Call npm install
#  command: npm install
#  args:
#    chdir: /opt/node-red 

#- name: Setup permissions of the node-red installation
#  file: >
#    dest=/opt/node-red
#    owner=node-red
#    group=users
#    recurse=yes

- name: Setup a systemd service for node-red
  template: >
    src=nodered.service.j2
    dest=/lib/systemd/system/node-red.service

- name: Enable and start the node-red systemd service
  service: >
    name=node-red
    enabled=yes
    state=started

- name: Create nginx proxy
  template:
    src: nodered-nginx.conf
    dest: /etc/nginx/sites-available/node-red

- name: Enable node-red nginx config
  file:
    src: /etc/nginx/sites-available/node-red
    dest: /etc/nginx/sites-enabled/node-red
    state: link

- name: Restart node-RED
  service: >
    name=node-red
    state=restarted

- name: Restart nginx
  service: >
    name=nginx
    enabled=yes
    state=restarted
